config/routes.rb
Rails.application.routes.draw do
  root to: 'main#home'

  resources :contact_mes, only: %i[new create]
  resources :adds, only: %i[index show]
  resources :admin, only: :index

  namespace :admin do
    resources :slideshow_pictures
    resources :adds do
      resources :add_images, only: %i[new create destroy]
    end
    resources :contact_mes, only: %i[index destroy] do
      patch 'contacted', on: :member
    end
  end
end

app/models/add.rb
class Add < ApplicationRecord
  has_many :add_images, dependent: :destroy
  mount_uploader :main_image, ImageUploader
  validate :image_present

  accepts_nested_attributes_for :add_images

  private

  def image_present
    errors.add(:main_image, 'must present') if main_image.url.nil? || main_image.url.empty?
  end
end

app/models/add_image.rb
class AddImage < ApplicationRecord
  belongs_to :add
  mount_uploader :image, ImageUploader
  validate :image_present
  default_scope { order(:draw_order) }

  private

  def image_present
    errors.add(:image, 'must present') if image.url.nil? || image.url.empty?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_me.rb
class ContactMe < ApplicationRecord
  validates :email, presence: true, unless: ->(contact_me) { contact_me.phone_number.present? }
  validates :phone_number, presence: true, unless: ->(contact_me) { contact_me.email.present? }
end

app/models/slideshow_picture.rb
class SlideshowPicture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validate :image_present

  private

  def image_present
    errors.add(:image, 'must present') if image.url.nil? || image.url.empty?
  end
end

app/controllers/adds_controller.rb
class AddsController < ApplicationController
  def index
    @adds = Add.all.where(active: true)
    @search = params
    @adds = @adds.where(for_rent: true) if @search[:for_rent] == 'true' && @search[:for_sale] != 'true'
    @adds = @adds.where(for_sale: true) if @search[:for_sale] == 'true' && @search[:for_rent] != 'true'
    case @search[:rooms]
    when '1+1'
      @adds = @adds.where(rooms: 1)
    when '2+1'
      @adds = @adds.where(rooms: 2)
    when '3+1'
      @adds = @adds.where(rooms: 3)
    when '4+1++'
      @adds = @adds.where(rooms: 4..1000)
    end
    @adds = @adds.order(price_tl: :asc) if @search[:price] == '↑'
    @adds = @adds.order(price_tl: :desc) if @search[:price] == '↓'
  end

  def show
    @add = Add.find(params[:id])
  end
end

app/controllers/admin/add_images_controller.rb
class Admin::AddImagesController < AdminController
  before_action :find_add

  def new
    @add_image = @add.add_images.new
  end

  def create
    @add_image = @add.add_images.new(add_image_params)

    if @add_image.save
      redirect_to edit_admin_add_path(@add)
    else
      render :new
    end
  end

  def destroy
    @add_image = AddImage.find(params[:id])
    @add_image.destroy
    redirect_to edit_admin_add_path(@add)
  end

  private

  def find_add
    @add = Add.find(params[:add_id])
  end

  def add_image_params
    params.require(:add_image).permit(:id, :add_id, :image, :image_cache, :remove_image, :draw_order, :images_order)
  end
end

app/controllers/admin/adds_controller.rb
class Admin::AddsController < AdminController
  def index
    @adds = Add.all
  end

  def new
    @add = Add.new
  end

  def create
    @add = Add.new(add_params)
    if @add.save
      redirect_to admin_adds_path
    else
      render :new
    end
  end

  def edit
    @add = Add.find(params[:id])
    render :new
  end

  def update
    @add = Add.find(params[:id])
    if @add.update(add_params)
      redirect_to admin_adds_path
    else
      render :new
    end
  end

  def destroy
    @add = Add.find(params[:id])
    @add.destroy
    redirect_to admin_adds_path
  end

  private

  def add_params
    params.require(:add).permit(:id, :active, :main_image, :main_image_cache, :remove_main_image, :description, :house, :flat,
                                :for_rent, :for_sale, :price_tl, :price_usd, :price_rub, :price_eur, :square_brut, :square_net,
                                :rooms, :living_rooms, :building_age, :floor, :max_floor, :heating, :number_of_bathrooms, :furnished,
                                :credit_available, :video_call_available, :elevator, :site, :header, :aidat, add_images_attributes: %i[id draw_order])
  end
end

app/controllers/admin/contact_mes_controller.rb
class Admin::ContactMesController < AdminController
  def index
    @contact_mes = ContactMe.all.order(contacted: :asc, created_at: :desc)
  end

  def contacted
    @contact_me = ContactMe.find(params[:id])
    contacted = @contact_me.contacted ? false : true
    @contact_me.update(contacted: contacted)

    redirect_to admin_contact_mes_path
  end

  def destroy
    @contact_me = ContactMe.find(params[:id])
    @contact_me.destroy

    redirect_to admin_contact_mes_path
  end
end

app/controllers/admin/slideshow_pictures_controller.rb
class Admin::SlideshowPicturesController < AdminController
  def index
    @slideshow_pictures = SlideshowPicture.all
  end

  def new
    @slideshow_picture = SlideshowPicture.new
    @slideshow_picture.active = true
  end

  def create
    @slideshow_picture = SlideshowPicture.new(slideshow_picture_params)
    if @slideshow_picture.save
      redirect_to admin_slideshow_pictures_path
    else
      render :new
    end
  end

  def edit
    @slideshow_picture = SlideshowPicture.find(params[:id])
    render :new
  end

  def update
    @slideshow_picture = SlideshowPicture.find(params[:id])
    if @slideshow_picture.update(slideshow_picture_params)
      redirect_to admin_slideshow_pictures_path
    else
      render :new
    end
  end

  def destroy
    @slideshow_picture = SlideshowPicture.find(params[:id])
    @slideshow_picture.destroy
    redirect_to admin_slideshow_pictures_path
  end

  private

  def slideshow_picture_params
    params.require(:slideshow_picture).permit(:id, :active, :image, :image_cache, :remove_image)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  http_basic_authenticate_with name: Rails.application.secrets.user, password: Rails.application.secrets.password
  before_action :authorize

  def index
    redirect_to admin_contact_mes_path
  end

  private

  def authorize
    session[:authorized] = true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'browser/aliases'
  Browser::Base.include(Browser::Aliases)

  before_action :set_locale
  before_action :determine_variant

  def default_url_options
    { lang: (I18n.locale unless I18n.locale == I18n.default_locale) }
  end

  private

  def set_locale
    I18n.locale = I18n.locale_available?(params[:lang]) ? params[:lang] : I18n.default_locale
  end

  def determine_variant
    Rails.logger.info("session: #{session[:use_mobile]}")
    request.variant = browser.mobile? ? :mobile : :desktop
  end
end

app/controllers/contact_mes_controller.rb
class ContactMesController < ApplicationController
  def new
    @contact_me = ContactMe.new unless @contact_me
  end

  def create
    @contact_me = ContactMe.new(contact_me_params)
    if @contact_me.save
      redirect_to root_path, notice: t('.success')
    else
      redirect_to new_contact_me_path
    end
  end

  private

  def contact_me_params
    params.require(:contact_me).permit(:phone_number, :email, :contact_with_whatsapp)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @slideshow_pictures = SlideshowPicture.where(active: true).to_a
    @slideshow_pictures.unshift(@slideshow_pictures.pop)
    @width = @slideshow_pictures.empty? ? '100%' : "#{@slideshow_pictures.count * 100}%"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adds/_add.html+mobile.slim
= link_to (add), target: "_blank" do
  .add-container-mobile
    .add-image-mobile = image_tag add.main_image.url
    .add-parameters-mobile
      .add-header = add.header if add.header
      .other-parameters
        = t('.house') + " | " if add.house
        = t('.flat') + " | " if add.flat
        = t('.for_sale') + " | " if add.for_sale
        = t('.for_rent') + " | " if add.for_rent
        = t('.price_tl') + add.price_tl.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | "
        = t('.price_usd') + add.price_usd.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_usd
        = t('.price_rub') + add.price_rub.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_rub
        = t('.price_eur') + add.price_eur.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_eur
        = t('.rooms') + add.rooms.to_s + "+" + add.living_rooms.to_s + " | " if add.square_net
        = t('.square_brut') + add.square_brut.to_s + " | " if add.square_brut
        = t('.square_net') + add.square_net.to_s + " | " if add.square_net
        = t('.building_age') + add.building_age.to_s + " | " if add.building_age
        = t('.floor') + add.floor.to_s + " | " if add.floor
        = t('.elevator') + ' | ' if add.elevator
        = t('.furnished') + " | " if add.furnished
        =  add.heating + " | " if add.heating
        = t('.credit_available') + " | " if add.credit_available
        = t('.video_call_available') if add.video_call_available

app/views/adds/_add.html.slim
= link_to (add), target: "_blank" do
  .add-container.pointer
    .add-image = image_tag add.main_image.url
    .add-parameters
      .add-header = add.header if add.header
      .other-parameters
        = t('.house') + " | " if add.house
        = t('.flat') + " | " if add.flat
        = t('.for_sale') + " | " if add.for_sale
        = t('.for_rent') + " | " if add.for_rent
        = t('.price_tl') + add.price_tl.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | "
        = t('.price_usd') + add.price_usd.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_usd
        = t('.price_rub') + add.price_rub.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_rub
        = t('.price_eur') + add.price_eur.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_eur
        = t('.rooms') + add.rooms.to_s + "+" + add.living_rooms.to_s + " | " if add.square_net
        = t('.square_brut') + add.square_brut.to_s + " | " if add.square_brut
        = t('.square_net') + add.square_net.to_s + " | " if add.square_net
        = t('.building_age') + add.building_age.to_s + " | " if add.building_age
        = t('.floor') + add.floor.to_s + " | " if add.floor
        = t('.elevator') + ' | ' if add.elevator
        = t('.furnished') + " | " if add.furnished
        =  add.heating + " | " if add.heating
        = t('.credit_available') + " | " if add.credit_available
        = t('.video_call_available') if add.video_call_available

app/views/adds/index.html+mobile.slim
.catalogue
  .add-filter-mobile
    = form_tag adds_path, method: :get do
      .filter-option-mobile
        .option-name-mobile = t('.for_rent')
        .option-value-mobile
          = check_box_tag :for_rent, true, @search[:for_rent], class: 'check'
      .filter-option-mobile
        .option-name-mobile = t('.for_sale')
        .option-value-mobile
          = check_box_tag :for_sale, true, @search[:for_sale], class: 'check'
      .filter-option-mobile
        .option-name-mobile = t('.rooms')
        .option-value-mobile
          = select_tag :rooms, options_for_select(["", "1+1", "2+1", "3+1", "4+1++"], @search[:rooms]), class: 'select'
      .filter-option-mobile
        .option-name-mobile = t('.price')
        .option-value-mobile
          = select_tag :price, options_for_select(["", "↑", "↓"], @search[:price]), class: 'select'
      .submit = button_tag t('.submit'), name: nil
      .hidden
        = select_tag :lang, options_for_select(["tr", "en", "ru"], params[:lang])
  .adds-mobile
    = render @adds

app/views/adds/index.html.slim
.catalogue
  .add-filter
    = form_tag adds_path, method: :get do
      .filter-options
        .filter-option
          .option-name = t('.for_rent')
          = check_box_tag :for_rent, true, @search[:for_rent], class: 'check'
        .filter-option
          .option-name = t('.for_sale')
          = check_box_tag :for_sale, true, @search[:for_sale], class: 'check'
        .filter-option
          .option-name = t('.rooms')
          = select_tag :rooms, options_for_select(["", "1+1", "2+1", "3+1", "4+1++"], @search[:rooms]), class: 'select'
        .filter-option
          .option-name = t('.price')
          = select_tag :price, options_for_select(["", "↑", "↓"], @search[:price]), class: 'select'
      .submit = button_tag t('.submit'), name: nil
      .hidden
        = select_tag :lang, options_for_select(["tr", "en", "ru"], params[:lang])
  .adds
    = render @adds

app/views/adds/show.html+mobile.slim
  .add-show-top-mobile
    .add-show-images-mobile
      .chosen-image
        = image_tag @add.main_image.url, class: "add-show-image-active"
        = image_tag 'arrow_left.png', class: "add-arrow-left"
        = image_tag 'arrow_right.png', class: "add-arrow-right"
      - unless @add.add_images.empty?
        .add-show-img-select
          = image_tag @add.main_image.url, class: "add-show-image active-image"
          - @add.add_images.order(:draw_order).each do |add_image|
            = image_tag add_image.image.url, class: "add-show-image"
    .add-show-properties-mobile
      - if @add.header
        .add-show-property.add-header = @add.header
      .add-show-property
        = t('.id') + @add.id.to_s
      .add-show-property
        = t('.date') + @add.created_at.strftime("%d.%m.%Y").to_s
      - if @add.house
        .add-show-property
          = t('.house')
      - if @add.flat
        .add-show-property
          = t('.flat')
      - if @add.for_sale
        .add-show-property
          = t('.for_sale')
      - if @add.for_rent
        .add-show-property
          = t('.for_rent')
      .add-show-property
        = t('.price_tl') + @add.price_tl.to_s.reverse.scan(/.{1,3}/).join(' ').reverse
      - if @add.price_usd
        .add-show-property
          = t('.price_usd') + @add.price_usd.to_s.reverse.scan(/.{1,3}/).join(' ').reverse
      - if @add.price_rub
        .add-show-property
          = t('.price_rub') + @add.price_rub.to_s.reverse.scan(/.{1,3}/).join(' ').reverse
      - if @add.price_eur
        .add-show-property
          = t('.price_eur') + @add.price_eur.to_s.reverse.scan(/.{1,3}/).join(' ').reverse
      - if @add.aidat
        .add-show-property
          = t('.aidat') + @add.aidat.to_s.reverse.scan(/.{1,3}/).join(' ').reverse
      - if @add.site
        .add-show-property = t('.site')
      - if @add.rooms
        .add-show-property
          = t('.rooms') + @add.rooms.to_s + "+" + @add.living_rooms.to_s
      - if @add.number_of_bathrooms
        .add-show-property
          = t('.number_of_bathrooms') + @add.number_of_bathrooms.to_s
      - if @add.square_brut
        .add-show-property
          = t('.square_brut') + @add.square_brut.to_s
      - if @add.square_net
        .add-show-property
          = t('.square_net') + @add.square_net.to_s
      - if @add.building_age  
        .add-show-property
          = t('.building_age') + @add.building_age.to_s
      - if @add.max_floor
        .add-show-property
          = t('.max_floor') + @add.max_floor.to_s
      - if @add.floor
        .add-show-property
          = t('.floor') + @add.floor.to_s
      -if @add.elevator
        .add-show-property
          = t('.elevator')
      - if @add.furnished
        .add-show-property
          = t('.furnished')
      - if @add.credit_available  
        .add-show-property
          = t('.credit_available')
      - if @add.video_call_available
        .add-show-property
          = t('.video_call_available')
      - if @add.description
        .add-show-property 
          .add-show-title = t('.description')
          = simple_format(@add.description)
  //- if @add.description
  //  .add-show-description = simple_format(@add.description)

app/views/admin/add_images/new.html.slim
= form_with model: [:admin, @add, @add_image], local: true, class: 'admin-form' do |f|
  = image_tag @add_image.image.url, class: "admin-form-avatar" if @add_image.image?
  .file
    = f.hidden_field :image_cache
    = f.file_field :image, class: "admin-form-file"

  .add-field
    = f.label :draw_order
    = f.number_field :draw_order

  .submit
    = f.submit t('.submit')

app/views/admin/adds/_add.html.slim
.add-container
  .add-image = image_tag add.main_image.url
  .add-parameters
    .add-header = add.header if add.header
    .other-parameters
      = t('.house') + " | " if add.house
      = t('.flat') + " | " if add.flat
      = t('.for_sale') + " | " if add.for_sale
      = t('.for_rent') + " | " if add.for_rent
      = t('.price_tl') + add.price_tl.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | "
      = t('.price_usd') + add.price_usd.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_usd
      = t('.price_rub') + add.price_rub.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_rub
      = t('.price_eur') + add.price_eur.to_s.reverse.scan(/.{1,3}/).join(' ').reverse + " | " if add.price_eur
      = t('.rooms') + add.rooms.to_s + "+" + add.living_rooms.to_s + " | " if add.square_net
      = t('.square_brut') + add.square_brut.to_s + " | " if add.square_brut
      = t('.square_net') + add.square_net.to_s + " | " if add.square_net
      = t('.building_age') + add.building_age.to_s + " | " if add.building_age
      = t('.floor') + add.floor.to_s + " | " if add.floor
      = t('.elevator') + ' | ' if add.elevator
      = t('.furnished') + " | " if add.furnished
      =  add.heating + " | " if add.heating
      = t('.credit_available') + " | " if add.credit_available
      = t('.video_call_available') if add.video_call_available
    .add-links
      = link_to t('.edit'), edit_admin_add_path(add)
      = link_to t('.delete'), admin_add_path(add), method: :delete

app/views/admin/adds/index.html.slim
.admin-adds
  .new-add = link_to t('.new'), new_admin_add_path
  = render @adds

app/views/admin/adds/new.html.slim
= form_with model: [:admin, @add], local: true, class: 'admin-add-form' do |f|
  = image_tag @add.main_image.url, class: "admin-form-avatar" if @add.main_image.url

  .file
    = f.hidden_field :main_image_cache
    = f.file_field :main_image, class: "admin-form-file"

  .admin-add-images
    = f.fields_for :add_images do |fi|
      .admin-add-image
        = image_tag fi.object.image.url, class: "admin-form-avatar" if fi.object.image?
        = fi.label :draw_order
        = fi.number_field :draw_order
        = link_to t('.delete_add_image'), admin_add_add_image_path(@add, fi.object), method: 'delete'

  = link_to t('.new_add_image'), new_admin_add_add_image_path(@add) if action_name == 'edit'

  .add-field style="margin-top: 20px;"
    = f.label :header
    = f.text_field :header

  .add-two-checks.add-field
    .admin-check.add-field
      = f.label :house
      = f.check_box :house, class: 'check'
    .admin-check.add-field
      = f.label :flat
      = f.check_box :flat, class: 'check'

  .add-two-checks.add-field
    .admin-check.add-field
      = f.label :for_rent
      = f.check_box :for_rent, class: 'check'
    .admin-check.add-field
      = f.label :for_sale
      = f.check_box :for_sale, class: 'check'

  .add-field
    = f.label :price_tl, required: true
    = f.number_field :price_tl

  .add-field
    = f.label :price_usd
    = f.number_field :price_usd

  .add-field
    = f.label :price_rub
    = f.number_field :price_rub

  .add-field
    = f.label :price_eur
    = f.number_field :price_eur
  
  .add-field
    = f.label :aidat
    = f.number_field :aidat

  .admin-check.add-field
      = f.label :site
      = f.check_box :site, class: 'check'

  .add-field
    = f.label :square_brut
    = f.number_field :square_brut

  .add-field
    = f.label :square_net
    = f.number_field :square_net

  .add-field.add-rooms
    = t('.rooms')
    = f.number_field :rooms
    |  + 
    = f.number_field :living_rooms

  .add-field
    = f.label :number_of_bathrooms
    = f.number_field :number_of_bathrooms

  .add-field.admin-check
    = f.label :furnished
    = f.check_box :furnished, class: 'check'

  .add-field
    = f.label :floor
    = f.number_field :floor
  
  .add-field
    = f.label :max_floor
    = f.number_field :max_floor

  .admin-check.add-field
    = f.label :elevator
    = f.check_box :elevator, class: 'check'
  
  .add-field
    = f.label :building_age
    = f.number_field :building_age

  .add-field
    = f.label :heating
    = f.text_field :heating

  .add-field.admin-check
    = f.label :credit_available
    = f.check_box :credit_available, class: 'check'
  
  .add-field.admin-check
    = f.label :video_call_available
    = f.check_box :video_call_available, class: 'check'

  .add-field.admin-check
    = f.label :active
    = f.check_box :active, class: 'check'

  .add-field.add-description
    = f.label :description
  .add-field.add-description
    = (f.text_area :description, cols: '60', rows: '10').html_safe

  .submit
    = f.submit t('.submit')

app/views/admin/contact_mes/_contact_me.html.slim
.admin-contact-me
  .admin-contact-info
    - if contact_me.email.present?
      .admin-email
        = t('.email')
        = contact_me.email
    - if contact_me.phone_number.present?
      .admin-phone
        = t('.phone_number')
        = contact_me.phone_number
    - if contact_me.contact_with_whatsapp && contact_me.phone_number.present?
      .admin-whatsapp = t('.contact_with_whatsapp')
  .admin-contacted
    = link_to t(".contacted"), contacted_admin_contact_me_path(contact_me), method: :patch
    = check_box_tag :contacted, contact_me.contacted, contact_me.contacted, disabled: true, class: 'check'
  .admin-delete
    = link_to t(".delete"), admin_contact_me_path(contact_me), method: :delete

app/views/admin/contact_mes/index.html.slim
.contact-mes
  = render @contact_mes

app/views/admin/slideshow_pictures/_slideshow_picture.html.slim
.slideshow_picture  
  = image_tag slideshow_picture.image.url
  .checkbox
    = t(".active")
    = check_box_tag :active, slideshow_picture.active, slideshow_picture.active, disabled: true
  .admin_links
    = link_to t('.edit'), edit_admin_slideshow_picture_path(slideshow_picture)
    = link_to t('.delete'), admin_slideshow_picture_path(slideshow_picture), method: :delete

app/views/admin/slideshow_pictures/index.html.slim
.slideshow_pictures
  = render @slideshow_pictures

  = link_to t(".create"), new_admin_slideshow_picture_path, class: 'pre-footer'

app/views/admin/slideshow_pictures/new.html.slim
= form_with model: [:admin, @slideshow_picture], local: true, class: 'admin-form' do |f|
  = image_tag @slideshow_picture.image.url, class: "admin-form-avatar" if @slideshow_picture.image?
  .admin-check
    = f.label :active
    = f.check_box :active, class: 'check'
  .file
    = f.hidden_field :image_cache
    = f.file_field :image, class: "admin-form-file"

  .submit
    = f.submit t('.submit')

app/views/contact_mes/new.html.slim
= form_for @contact_me, local: true do |form|
  .text-field
    = form.label :phone_number
    = form.text_field :phone_number

  .text-field
    = form.label :email
    = form.text_field :email

  .whatsapp
    = form.check_box :contact_with_whatsapp, class: :check
    = form.label :contact_with_whatsapp
  
  .submit
    = form.submit

app/views/layouts/admin.html+mobile.slim
doctype html
html.mobile
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    title Ethereal
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application',
      media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body.mobile
    = render 'shared/nav'
    .admin-wrap.page-wrap
      = render 'shared/admin_menu'
      = yield
    = render 'shared/footer'

app/views/shared/_admin_menu.html.slim
.admin-menu
  = link_to (t('.contact_mes') + " (#{ContactMe.where(contacted: false).count})"), admin_contact_mes_path
  = link_to t('.adds'), admin_adds_path
  = link_to t('.slideshow_pictures'), admin_slideshow_pictures_path

app/views/shared/_nav.html+mobile.slim
div class="nav"
  = link_to (root_path) do
    .logo-mobile
      = image_tag "logo.png"
      .title-mobile = image_tag "title.png"
  .menus
    .lang
      .current-lang
        | Eng
      ul class="lang-options hidden-space"
        li class="lang-option" id="en" En
        li class="lang-option" id="ru" Ru
        li class="lang-option" id="tr" Tr

    = image_tag "menu-bar.png", class: 'menu-bar'

  .nav-links-mobile.hidden
    - if current_page?(root_path)
      = link_to t('.home'), root_url, class: 'selected'
      = link_to t('.search'), adds_path
      = link_to t('.contact_me'), new_contact_me_path
      = link_to t('.admin'), admin_contact_mes_path if session[:authorized]
    - elsif current_page?(adds_path)
      = link_to t('.home'), root_url
      = link_to t('.search'), adds_path, class: 'selected'
      = link_to t('.contact_me'), new_contact_me_path
      = link_to t('.admin'), admin_contact_mes_path if session[:authorized]
    - elsif current_page?(new_contact_me_path)
      = link_to t('.home'), root_url
      = link_to t('.search'), adds_path
      = link_to t('.contact_me'), new_contact_me_path, class: 'selected'
      = link_to t('.admin'), admin_contact_mes_path if session[:authorized]
    - elsif request.url.include?('admin')
      = link_to t('.home'), root_url
      = link_to t('.search'), adds_path
      = link_to t('.contact_me'), new_contact_me_path
      = link_to t('.admin'), admin_contact_mes_path, class: 'selected'
    - else
      = link_to t('.home'), root_url
      = link_to t('.search'), adds_path
      = link_to t('.contact_me'), new_contact_me_path
      = link_to t('.admin'), admin_contact_mes_path if session[:authorized]

app/views/shared/_nav.html.slim
div class="nav"
  = link_to (root_path) do
    .logo
      = image_tag "logo.png"
      .title = image_tag "title.png"
  .nav-links
    - if current_page?(root_path)
      = link_to t('.home'), root_url, class: 'selected'
      = link_to t('.search'), adds_path
      = link_to t('.contact_me'), new_contact_me_path
      = link_to t('.admin'), admin_contact_mes_path if session[:authorized]
    - elsif current_page?(adds_path)
      = link_to t('.home'), root_url
      = link_to t('.search'), adds_path, class: 'selected'
      = link_to t('.contact_me'), new_contact_me_path
      = link_to t('.admin'), admin_contact_mes_path if session[:authorized]
    - elsif current_page?(new_contact_me_path)
      = link_to t('.home'), root_url
      = link_to t('.search'), adds_path
      = link_to t('.contact_me'), new_contact_me_path, class: 'selected'
      = link_to t('.admin'), admin_contact_mes_path if session[:authorized]
    - elsif request.url.include?('admin')
      = link_to t('.home'), root_url
      = link_to t('.search'), adds_path
      = link_to t('.contact_me'), new_contact_me_path
      = link_to t('.admin'), admin_contact_mes_path, class: 'selected'
    - else
      = link_to t('.home'), root_url
      = link_to t('.search'), adds_path
      = link_to t('.contact_me'), new_contact_me_path
      = link_to t('.admin'), admin_contact_mes_path if session[:authorized]
  .lang
    .current-lang
      | Eng
      ul class="lang-options hidden"
        li class="lang-option" id="en" En
        li class="lang-option" id="ru" Ru
        li class="lang-option" id="tr" Tr